# -*- coding: utf-8 -*-
"""Seed assessment_source_documents by mapping source files to programs."""
import json, os

BASE = os.getcwd()
with open(os.path.join(BASE, '_extracted.json'), encoding='utf-8') as f:
    RAW = json.load(f)

# Mapping: filename substring -> program code
FILE_TO_PROGRAM = [
    ('English_8 Dec', 'ENG'),
    ('ไทยเพื่อการสื่อสาร', 'THAI'),
    ('หลักสูตรภาษาจีน', 'CHI'),
    ('วิทย์กีฬา', 'SSE'),
    ('หลักสูตรนิเทศศาสตร์', 'DCA'),
    ('เทคโนโลยีดิจิทัลทางการแพทย์', 'DMI'),
    ('เทคโนโลยีสารสนเทศอัจฉริยะ', 'IIT'),
    ('ดิจิทัลคอนเทนต์และสื่อ', 'DCM'),
    ('MTA หรือ IMAG', 'IMAG'),
    ('รัฐศาสตร์ IR', 'IR'),
    ('การเมืองการปกครอง', 'POL'),
    ('รปศ', 'PA'),
    ('สาขาวิทยาศาสตร์.docx', 'SCI'),
    ('วิทยาศาสตร์ทางทะเล', 'MARSCI'),
    ('วิศวกรรมคอมพิวเตอร์และปัญญาประดิษฐ์', 'CEAI'),
    ('ปิโตรเคมี', 'PEP'),
    ('วิศวกรรมเคมี', 'CHEP'),
    ('วิศวกรรมเครื่องกล', 'MECH'),
    ('วิศวกรรมไฟฟ้า', 'EE'),
    ('วิศวกรรมโยธา', 'CIVIL'),
    ('อนามัยสิ่งแวดล้อม', 'ENVH'),
    ('นิติศาสตรบัณฑิต', 'LAW'),
    ('ศิลปะการประกอบอาชีพ', 'CUL'),
    ('การตลาดดิจิทัลและการสร้างแบรนด์', 'MKT'),
    ('โลจิสติกส์', 'LOG'),
    ('การจัดการการท่องเที่ยว', 'THM'),
    ('เศรษฐศาสตรบัณฑิต', 'ECON'),
    ('บัญชีบัณฑิต', 'ACC'),
    ('ออกแบบภายใน', 'INTD'),
    ('นานาชาติ', 'INTL'),
    ('PLOs-หลักสูตรวิทยาศาสตรบัณฑิต-สาขาวิทยาศาสต', 'AGRI'),
    ('เกษตรศาสตร์และนวัตกรร', 'AGRI'),
]

def find_program_code(fname):
    # Check truncated pattern first
    if 'การจัดการการท่องเที' in fname and 'การจัดการการท่องเที่ยว' not in fname:
        return 'THM'
    for substr, code in FILE_TO_PROGRAM:
        if substr in fname:
            return code
    return None

# Build VALUES for SQL insert
rows = []
for relpath, text in RAW.items():
    parts = relpath.split('\\', 1)
    if len(parts) < 2:
        continue
    folder, fname = parts
    if 'ยังไม่ได้ส่ง' in fname:
        continue
    ext = os.path.splitext(fname)[1].lower().lstrip('.')
    code = find_program_code(fname)
    # escape text for SQL
    safe_text = text.replace("'", "''")
    safe_fname = fname.replace("'", "''")
    safe_path = relpath.replace("\\", "/").replace("'", "''")
    safe_folder = folder.replace("'", "''")
    rows.append({
        'filename': fname,
        'file_path': relpath.replace('\\', '/'),
        'file_type': ext,
        'faculty_folder': folder,
        'program_code': code,
        'extracted_text': text,
    })

# Generate SQL
sql_parts = ["-- Seed source documents (33 files mapped to programs)",
             "-- Generated by seed_source_documents.py",
             ""]
# First get program IDs
sql_parts.append("WITH prog_lookup AS (")
sql_parts.append("  SELECT code, id FROM public.programs")
sql_parts.append(")")
sql_parts.append("INSERT INTO public.assessment_source_documents (program_id, filename, file_path, file_type, faculty_folder, extracted_text, parse_status)")
sql_parts.append("SELECT")
sql_parts.append("  pl.id,")
sql_parts.append("  v.filename,")
sql_parts.append("  v.file_path,")
sql_parts.append("  v.file_type,")
sql_parts.append("  v.faculty_folder,")
sql_parts.append("  v.extracted_text,")
sql_parts.append("  CASE WHEN v.program_code IS NULL THEN 'needs_manual' ELSE 'pending' END")
sql_parts.append("FROM (VALUES")

value_lines = []
for r in rows:
    code_sql = 'NULL' if r['program_code'] is None else f"'{r['program_code']}'"
    # Truncate extracted_text to avoid huge SQL — store first 50000 chars
    txt = r['extracted_text'][:50000].replace("'", "''")
    value_lines.append(
        f"  ({code_sql}, '{r['filename'].replace(chr(39), chr(39)+chr(39))}', "
        f"'{r['file_path'].replace(chr(39), chr(39)+chr(39))}', "
        f"'{r['file_type']}', "
        f"'{r['faculty_folder'].replace(chr(39), chr(39)+chr(39))}', "
        f"'{txt}')::record(filename text, file_path text, file_type text, faculty_folder text, extracted_text text, program_code text)"
    )
    # Actually, let's use a simpler approach with a different VALUES structure
# Restart with simpler approach
sql_parts = []
sql_parts.append("-- Seed source documents (metadata only; extracted_text kept in local _extracted.json)")
sql_parts.append("INSERT INTO public.assessment_source_documents (program_id, filename, file_path, file_type, faculty_folder, parse_status)")
sql_parts.append("SELECT pl.id, v.filename, v.file_path, v.file_type, v.faculty_folder, v.parse_status")
sql_parts.append("FROM (VALUES")

for i, r in enumerate(rows):
    code = r['program_code']
    code_sql = 'NULL::text' if code is None else f"'{code}'"
    fname = r['filename'].replace("'", "''")
    fpath = r['file_path'].replace("'", "''")
    ftype = r['file_type']
    folder = r['faculty_folder'].replace("'", "''")
    parse_st = 'needs_manual' if code is None else 'pending'
    sep = ',' if i < len(rows)-1 else ''
    sql_parts.append(f"  ({code_sql}, '{fname}', '{fpath}', '{ftype}', '{folder}', '{parse_st}'){sep}")

sql_parts.append(") AS v(program_code, filename, file_path, file_type, faculty_folder, parse_status)")
sql_parts.append("LEFT JOIN public.programs pl ON pl.code = v.program_code;")

sql = '\n'.join(sql_parts)
out = os.path.join(BASE, 'migrations', '002_seed_source_documents.sql')
with open(out, 'w', encoding='utf-8') as f:
    f.write(sql)
print(f"SQL written to {out}  [{len(sql)} chars, {len(rows)} rows]")

# Print mapping summary
mapped = sum(1 for r in rows if r['program_code'])
unmapped = [r['filename'] for r in rows if r['program_code'] is None]
print(f"Mapped: {mapped}/{len(rows)}")
if unmapped:
    print("UNMAPPED:")
    for f in unmapped:
        print(f"  {f}")
