-- Update parse_status and confidence for all source documents
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 0.91 WHERE filename = 'LOs Coop Ed_English_8 Dec 2024.pdf';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'LOs-ของรายวิชาสหกิจศึกษา-67-ไทยเพื่อการสื่อสาร.pdf';
UPDATE public.assessment_source_documents SET parse_status = 'needs_manual', extraction_confidence = 0.3 WHERE filename = 'ผลลัพธ์การเรียนรู้ที่คาดหวังของหลักสูตรภาษาจีน.pdf';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'LO สหกิจหลักสูตรเศรษฐศาสตรบัณฑิต.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา(หลักสูตรบัญชีบัณฑิต-ปรับปรุง-2567).docx';
UPDATE public.assessment_source_documents SET parse_status = 'needs_manual', extraction_confidence = 0.1 WHERE filename = 'ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา-ออกแบบภายใน.xlsx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา หลักสูตรบริหารธุรกิจบัณฑิต หลักสูตรนานาชาติ (หลักสูตรปรับปรุง พ.ศ. 2565) (1).docx';
UPDATE public.assessment_source_documents SET parse_status = 'needs_manual', extraction_confidence = 0.5 WHERE filename = 'PLOs-หลักสูตรวิทยาศาสตรบัณฑิต-สาขาวิทยาศาสต.docx';
UPDATE public.assessment_source_documents SET parse_status = 'needs_manual', extraction_confidence = 0.5 WHERE filename = 'หัวข้อประเมินตาม PLOs เกษตรศาสตร์และนวัตกรร.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'แบบประเมินสหกิจศึกษาที่สอดคล้องกับ LOs รายวิชาสหกิจศึกษา (วิทย์กีฬา).pdf';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 0.91 WHERE filename = '1.ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา หลักสูตรนิเทศศาสตร์.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 0.96 WHERE filename = '2.ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา หลักสูตรเทคโนโลยีดิจิทัลทางการแพทย์ พ.ศ.67.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 0.96 WHERE filename = '3.ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษาหลักสูตรเทคโนโลยีสารสนเทศอัจฉริยะ (IIT).pdf';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 0.85 WHERE filename = '4.หลักสูตรดิจิทัลคอนเทนต์และสื่อ.pdf';
UPDATE public.assessment_source_documents SET parse_status = 'needs_manual', extraction_confidence = 0.3 WHERE filename = '5.PLO ของ MTA หรือ IMAG.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 0.78 WHERE filename = 'LO และแบบสอบถาม - หลักสูตรรัฐศาสตร์ IR 2567.docx';
UPDATE public.assessment_source_documents SET parse_status = 'needs_manual', extraction_confidence = 0.5 WHERE filename = 'แบบประเมินสหกิจ หลักสูตรการเมืองการปกครอง.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 0.68 WHERE filename = 'แบบประเมินสหกิจหลักสูตร รปศ.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'หลักสูตรวิทยาศาสตรบัณฑิต สาขาวิทยาศาสตร์.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 0.97 WHERE filename = 'หลักสูตรวิทยาศาสตร์ทางทะเล_CLO_สหกิจศึกษา_JR310.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา หลักสูตรวิศวกรรมคอมพิวเตอร์และปัญญาประดิษฐ์ พ.ศ.67.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา-ปิโตรเคมีฯ.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา-วิศวกรรมเคมีฯ.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา-วิศวกรรมเครื่องกลฯ.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา-หลักสูตรวิศวกรรมไฟฟ้า-พ.ศ.2567.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'หลักสูตรวิศวกรรมศาสตรบัณฑิต สาขาวิศวกรรมโยธา ปรังปรุงปีการศึกษา 2567  .docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 0.82 WHERE filename = 'ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา อนามัยสิ่งแวดล้อม.pdf';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'หลักสูตรนิติศาสตรบัณฑิต หลักสูตรปรับปรุง ปีการศึกษา ๒๕๖๗  .docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'LO สหกิจหลักสูตรศิลปะการประกอบอาชีพ.pdf';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'ผลลัพธ์การเรียนรู้ของวิชาสหกิจศึกษา หลักสูตรการตลาดดิจิทัลและการสร้างแบรนด์.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'แบบประเมินรายวิชาสหกิจศึกษาตาม LO หลักสูตรการจัดการโลจิสติกส์_ส่ง.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'แบบประเมินสหกิจฯ สาขาการจัดการการท่องเที.docx';
UPDATE public.assessment_source_documents SET parse_status = 'parsed', extraction_confidence = 1.0 WHERE filename = 'แบบประเมินสหกิจฯ สาขาการจัดการการท่องเที่ยวและการโรงแรม (updated 30 Jan 2025).pdf';