// Migration 023: G11 — apply the full rubric-shortening rewrite (232 questions,
// 928 assessment_options.description_th rows) generated 2026-09-12.
//
// This supersedes migrations/020_rubric_rewrites.mjs (a partial, never-applied
// hand-picked sample of ~46 options) and migrations/020_shorten_rubric_descriptions.mjs
// (the runner for that sample) — this script covers ALL 928 options with descriptions
// across all 30 programs, generated by systematic review documented in
// migrations/g11_batches/batch_*_notes.md.
//
// Source of truth for the new text: migrations/g11_batches/g11_final_updates.json
// (array of { option_id, description_th_new }), built by merging
// migrations/g11_batches/batch_0..4_rewritten.json after human QA:
//   - verified row/question counts match the DB survey (928 rows, 232 questions)
//   - verified no question has duplicate descriptions across its 4 levels
//   - verified no "description == question_text with zero qualifier" bug remains
//   - spot-checked flagged fixes in batch_0/batch_3 notes (added missing level-4
//     qualifiers on EE LO12 and 6 CIVIL questions; fixed a content mismatch on
//     CIVIL LO6 level 3 that had been copy-pasted from an unrelated question)
//
// Safety (same pattern as migrations/020_shorten_rubric_descriptions.mjs):
//   - Every distinct template touched gets a template_revisions snapshot BEFORE
//     any UPDATE, using the exact same snapshot query as
//     web/src/app/programs/[programId]/edit/actions.ts:snapshotCurrent() — this
//     keeps the /programs/{programId}/history "restore" button working.
//   - Runs in a single transaction; rolls back on any error or row-count mismatch.
//   - --dry-run previews counts/programs/char-reduction without writing.
//
// Usage:
//   node migrations/023_g11_apply_full_rubric_shortening.mjs --dry-run
//   node migrations/023_g11_apply_full_rubric_shortening.mjs --apply

import pg from "pg";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const APPLY = process.argv.includes("--apply");
const NOTE = "ย่อคำอธิบาย rubric (G11) — 2569-09-12";

const envText = fs.readFileSync(path.join(__dirname, "..", "web", ".env.local"), "utf8");
const DATABASE_URL = envText.match(/DATABASE_URL=(.+)/)[1].trim();

const updatesPath = path.join(__dirname, "g11_batches", "g11_final_updates.json");
const updates = JSON.parse(fs.readFileSync(updatesPath, "utf8"));

const pool = new pg.Pool({ connectionString: DATABASE_URL, ssl: { rejectUnauthorized: false } });

// Exact same snapshot query as web/src/app/programs/[programId]/edit/actions.ts
const SNAPSHOT_SQL = `
  SELECT
    t.id, t.title, t.course_codes, t.scale_status, t.source_layout,
    COALESCE(
      json_agg(
        json_build_object(
          'id', s.id, 'title_th', s.title_th, 'part', COALESCE(s.part,1), 'sequence', s.sequence,
          'questions', COALESCE((
            SELECT json_agg(
              json_build_object(
                'id', q.id, 'lo_code', q.lo_code, 'text', q.text, 'text_en', q.text_en,
                'plo_refs', q.plo_refs, 'sequence', q.sequence,
                'options', COALESCE((
                  SELECT json_agg(
                    json_build_object('id', o.id, 'score', o.score, 'label_th', o.label_th,
                      'label_en', o.label_en, 'description_th', o.description_th,
                      'description_en', o.description_en, 'sequence', o.sequence)
                    ORDER BY o.sequence
                  )
                  FROM assessment_options o WHERE o.question_id = q.id
                ), '[]'::json)
              )
              ORDER BY q.sequence
            )
            FROM evaluation_questions q WHERE q.section_id = s.id
          ), '[]'::json)
        )
        ORDER BY s.sequence
      ) FILTER (WHERE s.id IS NOT NULL),
      '[]'::json
    ) AS sections
  FROM evaluation_templates t
  LEFT JOIN assessment_sections s ON s.template_id = t.id
  WHERE t.id = $1
  GROUP BY t.id`;

const ids = updates.map((u) => u.option_id);

const { rows: targets } = await pool.query(
  `SELECT o.id AS oid, o.description_th AS old, q.template_id, p.code AS program
   FROM assessment_options o
   JOIN evaluation_questions q ON q.id = o.question_id
   JOIN evaluation_templates t ON t.id = q.template_id
   JOIN programs p ON p.id = t.program_id
   WHERE o.id = ANY($1::uuid[])`,
  [ids]
);

if (targets.length !== ids.length) {
  const found = new Set(targets.map((r) => r.oid));
  console.error("หยุด: หา option เหล่านี้ไม่พบในฐานข้อมูล");
  console.error(ids.filter((i) => !found.has(i)));
  await pool.end();
  process.exit(1);
}

const oldByOid = new Map(targets.map((r) => [r.oid, r.old ?? ""]));
const templates = [...new Set(targets.map((r) => r.template_id))];
const programs = [...new Set(targets.map((r) => r.program))].sort();

const oldChars = updates.reduce((s, u) => s + (oldByOid.get(u.option_id)?.trim().length ?? 0), 0);
const newChars = updates.reduce((s, u) => s + u.description_th_new.length, 0);

console.log(`ตัวเลือกที่จะแก้ : ${targets.length}`);
console.log(`template ที่แตะ  : ${templates.length}`);
console.log(`หลักสูตร (${programs.length}) : ${programs.join(", ")}`);
console.log(`ตัวอักษร         : ${oldChars.toLocaleString()} → ${newChars.toLocaleString()} (ลด ${Math.round((1 - newChars / oldChars) * 100)}%)`);

if (!APPLY) {
  console.log(`\n[dry-run] ยังไม่เขียนอะไรลงฐานข้อมูล — ใส่ --apply เพื่อรันจริง`);
  await pool.end();
  process.exit(0);
}

const client = await pool.connect();
try {
  await client.query("BEGIN");

  let snapshotted = 0;
  for (const templateId of templates) {
    const { rows } = await client.query(SNAPSHOT_SQL, [templateId]);
    if (!rows[0]) throw new Error(`snapshot ล้มเหลวสำหรับ template ${templateId}`);
    await client.query(
      `INSERT INTO template_revisions (template_id, kind, snapshot_json, note, created_at)
       VALUES ($1, 'edit', $2::jsonb, $3, now())`,
      [templateId, JSON.stringify(rows[0]), NOTE]
    );
    snapshotted++;
  }
  console.log(`snapshot แล้ว ${snapshotted} template`);

  let updated = 0;
  for (const { option_id, description_th_new } of updates) {
    const { rowCount } = await client.query(
      `UPDATE assessment_options SET description_th = $2, updated_at = now() WHERE id = $1`,
      [option_id, description_th_new]
    );
    updated += rowCount;
  }
  console.log(`อัปเดตคำอธิบายแล้ว ${updated} ตัวเลือก`);

  if (updated !== updates.length) throw new Error(`อัปเดตได้ ${updated} จาก ${updates.length} — rollback`);

  await client.query("COMMIT");
  console.log(`\nสำเร็จ — เปิด /programs/{programId}/history ของแต่ละหลักสูตรเพื่อดูเวอร์ชันก่อนย่อ`);
} catch (error) {
  await client.query("ROLLBACK");
  console.error("ล้มเหลว rollback แล้ว:", error.message);
  process.exitCode = 1;
} finally {
  client.release();
  await pool.end();
}
